export interface ArtistDto {
  idArtist: string;
  strArtist: string;
  strArtistStripped: string | null;
  strArtistAlternate: string | null;
  strLabel: string;
  idLabel: string;
  intFormedYear: string;
  intBornYear: string;
  intDiedYear: string | null;
  strDisbanded: string | null;
  strStyle: string;
  strGenre: string;
  strMood: string;
  strWebsite: string;
  strFacebook: string;
  strTwitter: string;
  strGender: string;
  intMembers: string;
  strCountry: string;
  strCountryCode: string;
  strArtistThumb: string;
  strArtistLogo: string;
  strArtistCutout: string;
  strArtistClearart: string;
  strArtistWideThumb: string;
  strArtistFanart: string;
  strArtistFanart2: string;
  strArtistFanart3: string;
  strArtistFanart4: string;
  strArtistBanner: string;
  strMusicBrainzID: string;
  strISNIcode: string | null;
  strLastFMChart: string;
  intCharted: string;
  strLocked: string;
}

export interface SongDto {
  idTrack: string;
  idAlbum: string;
  idArtist: string;
  idLyric: string;
  idIMVDB: string | null;
  strTrack: string;
  strAlbum: string;
  strArtist: string;
  strArtistAlternate: string | null;
  intCD: string | null;
  intDuration: string;
  strGenre: string;
  strMood: string;
  strStyle: string;
  strTheme: string;
  intMusicVidViews: string;
  intMusicVidLikes: string;
  intMusicVidDislikes: string | null;
  intMusicVidFavorites: string;
  intMusicVidComments: string;
  intTrackNumber: string;
  intLoved: string;
  intScore: string;
  intScoreVotes: string;
  intTotalListeners: string;
  intTotalPlays: string;
  strMusicBrainzID: string;
  strMusicBrainzAlbumID: string;
  strMusicBrainzArtistID: string;
  strLocked: string;
}
